server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hoteldb
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true